#! /bin/bash
# This software is a part of the A.O.D apprepo project
# Copyright 2020 Alex Woroschilow (alex.woroschilow@gmail.com)
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
set -ex

PATH=${PATH}:${APPDIR}/opt/libreoffice6.4/program
export PATH=${PATH}

LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${APPDIR}/opt/libreoffice6.4/program
export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}

cd ${OWD}

case "$1" in
  '--writer') exec ${APPDIR}/opt/libreoffice6.4/program/swriter "$2" ;;
  '--spreadsheets')   exec ${APPDIR}/opt/libreoffice6.4/program/scalc "$2" ;;
  '--presentation')   exec ${APPDIR}/opt/libreoffice6.4/program/simpress "$2" ;;
  '--math')   exec ${APPDIR}/opt/libreoffice6.4/program/smath "$2" ;;
  '--base')   exec ${APPDIR}/opt/libreoffice6.4/program/sbase "$2" ;;
  *)   exec ${APPDIR}/opt/libreoffice6.4/program/soffice "$@" ;;
esac
